add all task of US joined mark
alex96dev/Easy-Meetup-with-Friends pull request #23
Opened 2024-03-12 13:49 UTC by alex96dev

- Define the logic to determine if an activity is joined by the user.
- Update the component to display the indicator on the activity card.
- Test the functionality across different pages to ensure consistency in displaying the indicator for joined activities.
- Integrate the logic into the frontend and backend systems to handle the display of the indicator.

2024-03-12 14:11 UTC, MerleMak requested changes
Nice job so far! 
I think 3 useStates are a bit excessive, maybe you can thing about creating one State as an object that contains all the info of the button color and text and joined true or false. 
Either way, try to go over the "joining logic" and reconsider what you really need. 
Tip: ChatGPT is a great helper for that :)

keep it up!

2024-03-12 14:11 UTC, MerleMak commented on components/DetailsCard/index.js
> +      <StyledJoinedmark>{joined.joined && <p>XX</p>}</StyledJoinedmark>
This seems more complicated than it needs to be. 
Why don't you make a useState that keeps a Boolean

`const [isJoined, setIsJoined] = useState(false)`

2024-03-12 15:43 UTC, alex96dev commented
Hi Merle, 
I just implemented your suggestions and I noticed that putting all 3 states in just 1 state as an object produced a significant higher amount of code due to the new syntax in order to update or calling the states.
Is this the way to go anyways?

2024-03-13 08:45 UTC, MerleMak reviewed
How about this? :)

2024-03-13 08:45 UTC, MerleMak commented on components/DetailsCard/index.js
> +        }));
```suggestion
        setJoinState((prevState) => ({
           setJoinState((prevState) => {
        const joinButtonColor = json.joined ? "red" : "green";
        const joinButtonText = json.joined ? "Disjoin" : "Join";

```

2024-03-13 08:45 UTC, MerleMak commented on components/DetailsCard/index.js
>          } else {
```suggestion
```

2024-03-13 08:45 UTC, MerleMak commented on components/DetailsCard/index.js
>          }
```suggestion
      return {
          ...prevState,
          isJoined: json.joined,
          joinButtonColor,
          joinButtonText,
        };
      });
```

2024-03-13 12:00 UTC, merged